#logging.file.name=logs/app.log
#logging.pattern.file=%d %p %c{1.} [%t] %m%n
#logging.pattern.console=%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n

---
spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ${CLEARDB_DATABASE_URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    initialization-mode: always
    platform: mysql

server:
  port: ${PORT}
  error:
    whitelabel:
      enabled: false
    path: /error

facility:
  orders:
    page-size: 15



